
all: serveur1-LaPaireDeSockets.c serveur2-LaPaireDeSockets.c serveur3-LaPaireDeSockets.c
	gcc -Wall serveur1-LaPaireDeSockets.c -o ../bin/serveur1-LaPaireDeSockets
	gcc -Wall serveur2-LaPaireDeSockets.c -o ../bin/serveur2-LaPaireDeSockets
	gcc -Wall serveur3-LaPaireDeSockets.c -o ../bin/serveur3-LaPaireDeSockets

clean:
	rm ../bin/serveur1-LaPaireDeSockets
	rm ../bin/serveur2-LaPaireDeSockets
	rm ../bin/serveur3-LaPaireDeSockets
